### ISSUE TITLE
Inconsistent tree diagram and plot in data exploration notebook

### ISSUE THREAD

**Issue by lesteve** [lesteve/scikit-learn-tutorial#9]
https://nbviewer.jupyter.org/github/lesteve/scikit-learn-tutorial/blob/master/rendered_notebooks/01_tabular_data_exploration.ipynb

![image](https://user-images.githubusercontent.com/1680079/67189463-8fb0b780-f3ee-11e9-916d-6feecc49890c.png)

You would expect the high `age` high `hours-per-week` to be "high-earning". This is what the 2d plot shows (in red). The `plot_tree` (tree diagram) says `value = [637, 572]` so in the same order as all the other leaves.

Not clear where the problem is, `plot_tree` (scikit-learn) or `plot_tree_decision_function` (function in the notebook).

**Comment by ogrisel** [comment]
Well I would rather say that this quadrant is "uncertain" / "equal odds" (rather than "high income"). There is a vast majority (~75%) of low income entries in the full dataset, this is not a balanced classification problem.

- 49 + 551 + 572 == 1172
- 1341 + 1850 + 637 == 3828

The tree is correct, the color code is a bit misleading.

**Comment by lesteve** [comment]
Moved to https://github.com/INRIA/scikit-learn-mooc/issues/3.
